services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: mini_ecom_api_prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=mini_ecom
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - mini_ecom_prod_network
    restart: always

  postgres:
    image: postgres:16-alpine
    container_name: mini_ecom_db_prod
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mini_ecom
    volumes:
      - mini_ecom_prod_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mini_ecom_prod_network
    restart: always

  redis:
    image: redis/redis-stack:latest
    container_name: mini_ecom_redis_prod
    ports:
      - "6379:6379"
    volumes:
      - mini_ecom_prod_redis_data:/data
    restart: always
    networks:
      - mini_ecom_prod_network

volumes:
  mini_ecom_prod_data:
  mini_ecom_prod_redis_data:

networks:
  mini_ecom_prod_network:
    driver: bridge
