services:
  postgres:
    image: postgres:16-alpine
    container_name: hospital-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mini_ecom
    ports:
      - "5432:5432"
    volumes:
      - mini_ecom_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mini_ecom_data:
